In [2]:
import pickle
import numpy as np
import pandas as pd

In [3]:
classifier_f = open('X.pickle?raw=true','rb')
X = pickle.load(classifier_f)
classifier_f.close()

classifier_f = open('y.pickle?raw=true','rb')
y = pickle.load(classifier_f)
classifier_f.close()

In [4]:
X[5][:]

array([ 1.08343016, -0.40109407])

In [5]:
y.head()

project_is_approved
0                    1
1                    0
2                    1
3                    0
4                    1

In [6]:
y = np.array(y[:])
y.shape

(182080, 1)

In [7]:
X.shape

(182080, 2)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
clf = GaussianNB()
clf.fit(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [25]:
test = pd.read_csv('test.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [26]:
val = test.iloc[:,[5,14]]
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
val.iloc[:, 0] = labelencoder.fit_transform(val.iloc[:, 0])
val[:5]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


project_grade_category  teacher_number_of_previously_posted_projects
0                       3                                             2
1                       0                                             1
2                       3                                             0
3                       3                                             0
4                       1                                             1

In [27]:
from sklearn.preprocessing import StandardScaler
sc_y = StandardScaler()
val = sc_y.fit_transform(val)

In [28]:
val[:5]

array([[ 1.08882872, -0.33147148],
       [-1.1886321 , -0.36720933],
       [ 1.08882872, -0.40294718],
       [ 1.08882872, -0.40294718],
       [-0.42947849, -0.36720933]])

In [29]:
y_pred = clf.predict_proba(val)

In [38]:
y_pred[:5]

array([[0.23770831, 0.76229169],
       [0.22706699, 0.77293301],
       [0.23544594, 0.76455406],
       [0.23544594, 0.76455406],
       [0.23233457, 0.76766543]])

In [42]:
y_pred = np.array(y_pred)

In [43]:
y_pred.shape

(78035, 2)

In [44]:
y_pred1 = y_pred[:,1]

In [45]:
y_pred1.shape

(78035,)

In [43]:
y_pred.transpose

<function ndarray.transpose>

In [47]:
d = {'id':test['id'],'project_is_approved':y_pred1[0]}
X = pd.DataFrame(d)
X.to_csv('teacher_sub.csv',index = False)

In [48]:
X.head()

id  project_is_approved
0  p233245             0.762292
1  p096795             0.762292
2  p236235             0.762292
3  p233680             0.762292
4  p171879             0.762292

In [ ]:
!kg submit 'teacher_sub.csv' -u lightsalsa -p 11QQqq!! -c donorschoose-application-screening -m "NB"