In [1]:
import pandas as pd
import numpy as np

In [27]:
train.head()

id                        teacher_id teacher_prefix school_state  \
0  p036502  484aaf11257089a66cfedc9461c6bd0a            Ms.           NV   
1  p039565  df72a3ba8089423fa8a94be88060f6ed           Mrs.           GA   
2  p233823  a9b876a9252e08a55e3d894150f75ba3            Ms.           UT   
3  p185307  525fdbb6ec7f538a48beebaa0a51b24f            Mr.           NC   
4  p013780  a63b5547a7239eae4c1872670848e61a            Mr.           CA   

  project_submitted_datetime project_grade_category  \
0        2016-11-18 14:45:59          Grades PreK-2   
1        2017-04-26 15:57:28             Grades 3-5   
2        2017-01-01 22:57:44             Grades 3-5   
3        2016-08-12 15:42:11             Grades 3-5   
4        2016-08-06 09:09:11             Grades 6-8   

            project_subject_categories  \
0                  Literacy & Language   
1    Music & The Arts, Health & Sports   
2  Math & Science, Literacy & Language   
3                      Health & Sports   
4                      Health & Sports   

            project_subject_subcategories  \
0                                Literacy   
1            Performing Arts, Team Sports   
2  Applied Sciences, Literature & Writing   
3                       Health & Wellness   
4                       Health & Wellness   

                                       project_title  \
0                           Super Sight Word Centers   
1                             Keep Calm and Dance On   
2                              Lets 3Doodle to Learn   
3  \"Kid Inspired\" Equipment to Increase Activit...   
4   We need clean water for our culinary arts class!   

                                     project_essay_1  \
0  Most of my kindergarten students come from low...   
1  Our elementary school is a culturally rich sch...   
2  Hello;\r\nMy name is Mrs. Brotherton. I teach ...   
3  My students are the greatest students but are ...   
4  My students are athletes and students who are ...   

                                     project_essay_2 project_essay_3  \
0  I currently have a differentiated sight word c...             NaN   
1  We strive to provide our diverse population of...             NaN   
2  We are looking to add some 3Doodler to our cla...             NaN   
3  The student's project which is totally \"kid-i...             NaN   
4  For some reason in our kitchen the water comes...             NaN   

  project_essay_4                           project_resource_summary  \
0             NaN  My students need 6 Ipod Nano's to create and d...   
1             NaN  My students need matching shirts to wear for d...   
2             NaN  My students need the 3doodler. We are an SEM s...   
3             NaN  My students need balls and other activity equi...   
4             NaN  My students need a water filtration system for...   

   teacher_number_of_previously_posted_projects  project_is_approved  
0                                            26                    1  
1                                             1                    0  
2                                             5                    1  
3                                            16                    0  
4                                            42                    1

In [39]:
trainer = train.iloc[:,[5,14]]
trainer.head(5)

project_grade_category  teacher_number_of_previously_posted_projects
0          Grades PreK-2                                            26
1             Grades 3-5                                             1
2             Grades 3-5                                             5
3             Grades 3-5                                            16
4             Grades 6-8                                            42

In [42]:
y = train.iloc[:,[15]]
y.head(5)

project_is_approved
0                    1
1                    0
2                    1
3                    0
4                    1

In [43]:
trainer['project_grade_category'].unique()

array(['Grades PreK-2', 'Grades 3-5', 'Grades 6-8', 'Grades 9-12'],
      dtype=object)

In [45]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
trainer.iloc[:, 0] = labelencoder.fit_transform(trainer.iloc[:, 0])

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [47]:
trainer['project_grade_category'].head(5)

0    3
1    0
2    0
3    0
4    1
Name: project_grade_category, dtype: int64

In [48]:
trainer.head(5)

project_grade_category  teacher_number_of_previously_posted_projects
0                       3                                            26
1                       0                                             1
2                       0                                             5
3                       0                                            16
4                       1                                            42

In [49]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(trainer)

In [51]:
X[:5,:]

array([[ 1.08343016,  0.52694675],
       [-1.19495526, -0.36540019],
       [-1.19495526, -0.22262468],
       [-1.19495526,  0.17000797],
       [-0.43549345,  1.09804879]])

In [2]:
import pickle

In [3]:
classifier_f = open('X.pickle','rb')
X = pickle.load(classifier_f)
classifier_f.close()

classifier_f = open('y.pickle','rb')
y = pickle.load(classifier_f)
classifier_f.close()

In [4]:
import keras

/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [5]:
from keras.models import Sequential
from keras.layers import Dense

In [6]:
cl = Sequential()

In [8]:
cl.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu', input_dim = 2))

In [9]:
cl.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))

In [10]:
cl.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))

In [12]:
cl.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [13]:
cl.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
cl.fit(X_train, y_train, batch_size = 10, epochs = 5)

Epoch 1/5
145664/145664 [==============================] - 124s 851us/step - loss: 0.4267 - acc: 0.8473
Epoch 2/5
145664/145664 [==============================] - 61s 417us/step - loss: 0.4247 - acc: 0.8474
Epoch 3/5
145664/145664 [==============================] - 61s 417us/step - loss: 0.4244 - acc: 0.8474
Epoch 4/5
145664/145664 [==============================] - 61s 420us/step - loss: 0.4244 - acc: 0.8474
Epoch 5/5
145664/145664 [==============================] - 62s 423us/step - loss: 0.4244 - acc: 0.8474


In [18]:
test = pd.read_csv('test.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [19]:
test.head(5)

id                        teacher_id teacher_prefix school_state  \
0  p233245  5724a0c3ce11008366fff36dab4b943c            Ms.           CA   
1  p096795  445619941dc7cbe81c7be109dc61a56a           Mrs.           SC   
2  p236235  e92a4902b1611a189643d6f12c51e6a0           Mrs.           SC   
3  p233680  8e92622d2985d3faac1de71609c4be72           Mrs.           IA   
4  p171879  91a3c89981f626d9a0d067c65fb186ce            Mr.           CA   

  project_submitted_datetime project_grade_category  \
0        2016-04-27 13:45:41          Grades PreK-2   
1        2016-04-28 12:43:56             Grades 3-5   
2        2016-04-29 21:16:05          Grades PreK-2   
3        2016-04-27 22:32:43          Grades PreK-2   
4        2016-04-27 18:59:15             Grades 6-8   

            project_subject_categories      project_subject_subcategories  \
0                     Music & The Arts                        Visual Arts   
1  Literacy & Language, Math & Science  Literature & Writing, Mathematics   
2                       Math & Science      Applied Sciences, Mathematics   
3                  Literacy & Language                           Literacy   
4      Music & The Arts, Special Needs     Performing Arts, Special Needs   

                         project_title  \
0             Art Will Make You Happy!   
1            Keeping up with the TIMEs   
2  Building Bridges to Problem Solving   
3                    Classroom Library   
4                 Reeds so we can Read   

                                     project_essay_1  \
0  My 2nd grade students are amazing!  They are v...   
1  Students within the classroom work in small gr...   
2  My students share  a love of learning. These s...   
3  Reading is the gateway to the soul.  Guiding c...   
4  \"Mr. Reyes!  I need another reed!\"  I hear t...   

                                     project_essay_2  \
0  My class is made up of 12 boys and 12 girls.  ...   
1  My students are all very talented young indivi...   
2  My class consists of 14 energetic learners.  O...   
3  First graders enter the classroom each day rea...   
4  We have a diverse population with almost entir...   

                                     project_essay_3  \
0  My second grade class will really benefit from...   
1  We do a lot of small group, where the student ...   
2  These Fairy Tale Problem Solving STEM kits wil...   
3  Book bins will help to organize our classroom ...   
4  Each day in my class students consume supplies...   

                                     project_essay_4  \
0  The genorous donations to my project will make...   
1  This project is very important to my classroom...   
2  These materials will be help my students with ...   
3  When students begin the first grade, many are ...   
4  My students come from very troubled homes and ...   

                            project_resource_summary  \
0  My students need a drying rack for their art p...   
1  My students need Time Magazines for next year ...   
2  My students need to be mentally stimulated to ...   
3   My students need an organized classroom library.   
4  My students need reeds to perform in class eac...   

   teacher_number_of_previously_posted_projects  
0                                             2  
1                                             1  
2                                             0  
3                                             0  
4                                             1

In [22]:
val = test.iloc[:,[5,14]]

In [23]:
val.head(5)

project_grade_category  teacher_number_of_previously_posted_projects
0          Grades PreK-2                                             2
1             Grades 3-5                                             1
2          Grades PreK-2                                             0
3          Grades PreK-2                                             0
4             Grades 6-8                                             1

In [24]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
val.iloc[:, 0] = labelencoder.fit_transform(val.iloc[:, 0])

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [25]:
from sklearn.preprocessing import StandardScaler
sc_y = StandardScaler()
val = sc_y.fit_transform(val)

In [27]:
val[:5]

array([[ 1.08882872, -0.33147148],
       [-1.1886321 , -0.36720933],
       [ 1.08882872, -0.40294718],
       [ 1.08882872, -0.40294718],
       [-0.42947849, -0.36720933]])

In [28]:
y_pred = cl.predict(val)

In [29]:
y_pred[:5]

array([[0.82674026],
       [0.83730495],
       [0.8232431 ],
       [0.8232431 ],
       [0.8289711 ]], dtype=float32)

In [36]:
y_pred.transpose

<function ndarray.transpose>

In [39]:
d = {'id':test['id'],'project_is_approved':y_pred[:,0]}

In [40]:
X = pd.DataFrame(d)
X.to_csv('teacher_sub.csv',index = False)

In [42]:
df = pd.read_csv('teacher_sub.csv')
df.head()

id  project_is_approved
0  p233245             0.826740
1  p096795             0.837305
2  p236235             0.823243
3  p233680             0.823243
4  p171879             0.828971